### ISSUE TITLE
Other Preferences - Not Displaying

### ISSUE THREAD

**Issue by snakedog116** [StrykerSKS/SmartThingsPublic#1]
The "Other Preferences" Screen (last screen of the Ecobee (Connect) app). does not display any preferences, instead it shows "Lorum lpsum otherprefs" on a white screen.

**Comment by snakedog116** [comment]
I think I may have been using your old code again.

In anycase, I've pushed some changes. Minor stuff.

**Comment by StrykerSKS** [comment]
Must be as I don't even have an Other Preferences tab in the current version. I probably should just delete the old code from github so that it doesn't cause any confusion!
