### ISSUE TITLE
Add decimal place for Celsius temperatures

### ISSUE THREAD

**Issue by StrykerSKS** [StrykerSKS/SmartThingsPublic#10]
Add support for decimal places for Celsius values (out to one decimal place).

**Comment by StrykerSKS** [comment]
Should be covered in the latest version as well. Will await feedback from Celsius testing.

**Comment by snakedog116** [comment]
I've got decimals in some places, but not others:
- [x] when looking at the list of devices. I have decimals (Thermostat is reading 19.5, SmartThings is reading 19.4)
- [ ] The multi-tile does not have decimals _SmartThings limitation_
- [x] The arrows on the multi-tile move in full numbers. _Works for the down arrow in 0.5 increments, up arrow is 1.0 increments_
- [x] The outside temp has decimals. (The ecobee doesn't, but it's reading -6, the Smartthings is reading -5.3 even with rounding shouldn't that be -5 on the ecobee? Not sure if this is a coding issue or just ecobee's funny rounding)
- [x] the 'cool' set temp does not have decimals. (Although I don't have an AC unit so someone else should confirm if this one is working.) **Please someone with an AC unit, test this and let us know**
- [x] the 'heat' set temp does have decimals. but it reads 17.5, but my ecobee is reading 18.0. When I change the temp with the slider or arrows, the numbers sync up. Just seems the schedule numbers are off a bit?
- [ ] The sliders do not have decimals _SmartThings limitation_

**Comment by StrykerSKS** [comment]
Hmmm, the arrows should actually be moving in .5 increments when in Celsius. I added this specifically to make it more granular for Celsius users. It was working when I tested it. Can you double check the Live Logging to see if it is sending in .5 or 1.0 increments? I found the arrows to be very had to use and sometimes didn't register at all or sometimes double registered.

I was unable to get the multi-tile to show decimals no matter what I did. Even if the value that it was pulling from (`temperature`) was stored with a decimal it only presented as a whole number. I need to open a ticket with ST on this after testing some more.

Regarding the `cool` setting: The tiles may not update with decimals if the values have not changed. And even then you may have to wait a full poll cycle. (ST does not push updates to the client if the values have not changed in order to reduce the load.) So you probably have to change the cool setting manually for it to update, or wait for it to do a full update.

Regarding sliders: This is a limitation on the ST platform that they do not allow you to set the increments for the slider. We should all submit this as a feature request so that they will consider it in the future.

**Comment by snakedog116** [comment]
I just tested the up arrow again, and checked the 'recently' log:

Started at 18.5, went to 19.5 then 20.5.

Going back down it went to 20.0, 19.5, 19.05, 18.5

Looks like the down arrow is .5, but the up is 1.0

Tried it twice.

The rest look like issues with SmartThings, not your code. Do you want me to mark them as done?

**Comment by StrykerSKS** [comment]
Sure enough, I added the .5 in one spot and not the other. At least this one is a very easy fix!

You can leave the ST ones as open in case anyone looks at the issues, then they can read the threads to see that it is out of my control.
