### ISSUE TITLE
Need to implement setThermostatFanMode() and related functions

### ISSUE THREAD

**Issue by StrykerSKS** [StrykerSKS/SmartThingsPublic#11]
The current device type only has placeholder functions defined that do not function. Need to be implemented. This will be needed before it will be possible to set the fan mode from other SmartApps.

**Comment by StrykerSKS** [comment]
Beta release available in the v0.8.0-RC1 release on the beta branch for testing.

**Comment by ncsufire** [comment]
Here is what I have:

HVAC is in Auto with heat set to 68F and cool 76F.  

Here is what I saw:
1.  Fan changed from Auto to On also places a hold on the temperature; mine is set to temporary so it holds the current temperature settings until the next schedule change.
2.  Fan changed from On to Auto maintains the temperature hold on the temperature; mine is set to temporary so it maintains the hold of the current temperature until the next schedule change.

Is this expected behavior?  I was able to see the Fan change from Auto to On through the web portal.

**Comment by StrykerSKS** [comment]
The "Hold" staying on after each press seems to be consistent with how changing it from the web portal seems to be working. However, having the temperatures as part of the hold is slightly different behavior it seems.

The API docs stated that the temperatures were mandatory elements, but the API docs also don't list the fan: parameter at all. So I think I need to play with it and see if I can replicate the web portal behavior. (Although it is essentially the same either way since it is still a Hold behavior so the temps won't change.)

Interestingly, playing with the web portal version I noticed that clicking the Fan buttons (auto/on) always sets a permanent hold. Whereas my implementation is a little more flexible since it allows the fan change to be temporary. 

I'll need to try a few more tests to see if I can tweak it. But for now I think what I have gets the job done and is behaving as expected.

Btw, if you people are wanting to temporarily turn on the fan, then go back to the old settings then instead of click the fan button again (or calling fanAuto() ) they should use the resumeProgram capability instead.

**Comment by ncsufire** [comment]
At the thermostat do you have it set to a permeant hold or temporary?  Mine is set to temporary at the thermostat.

**Comment by StrykerSKS** [comment]
At the thermostat I have mine set to "ask each time" (or whatever the exact wording is).

**Comment by StrykerSKS** [comment]
Okay, after playing with the APIs some more tonight I think I might have a way forward to set the fan without it having to show as if it were changing the temperatures as well. The tricky part is doing this when an active hold is already running...

**Comment by StrykerSKS** [comment]
@ncsufire Can you play with this feature again? I've enhanced it so that it only should change the fan settings without impacting temperature.

**Comment by ncsufire** [comment]
Tested that it only changes the fan and not the temperature.  On my system the Fan: Circulate and Fan: Auto both place the Fan in auto on the thermostat, is this suppose to happen?  Here are screen shots of the Ecobee web portal; note to ensure what the Circulate did I made sure to go back and hit Resume Program before making my first state change Circulate:

Fan: Circulate
![fan_circualte](https://cloud.githubusercontent.com/assets/16526555/12861250/090f5ebe-cc30-11e5-9935-fa4ef11910b9.JPG)

Fan: On
![fan_on](https://cloud.githubusercontent.com/assets/16526555/12861256/0caea99e-cc30-11e5-9f11-3eb4ad318896.JPG)

Fan: Auto
![fan_auto](https://cloud.githubusercontent.com/assets/16526555/12861259/101f73e2-cc30-11e5-8d69-2f1fe560f2a2.JPG)

**Comment by StrykerSKS** [comment]
Yes, that is the expected behavior (for now).

The thing is that Ecobee doesn't implement a proper circulate mode. I contemplated a couple of options but it ended up being too much of a pain to implement. One option would have been to be to set the minimum fan run time to some value to cause it to stay on for a certain time. 

This seemed like the right approach, but it turns out you can't turn on this setting temporarily, so if you change it then it sets the setting for the whole thermostat. So, if I were to go that route I'd have to constantly keep track of the previous values and setting it back and forth. Didn't seem worth it.

I also debated leaving off the circulate all together, but since it is a part of the Thermostat capability in SmartThings, then it has to be implemented. 

So I really only had a few options:
- Implement it as a "do nothing" option
- Implement circulate as "on"
- Implement circulate as "auto"

I picked auto as it seemed most intuitive to me but I'm open to change it.

Also, for the next update to the UI before the 1.0 release, I'm planning to remove "circulate" from the rotation of the button since it really doesn't map to anything on the Ecobee side. But having it there for now allowed for testing to make sure it didn't break anything if called.

**Comment by ncsufire** [comment]
Thank you for the explanation.  If this is the expected state then I would
recommend closing this and reopen to work on circulate at a date tbd.
