### ISSUE TITLE
SmartApp shows success popup but fails to properly install if device types not installed

### ISSUE THREAD

**Issue by StrykerSKS** [StrykerSKS/SmartThingsPublic#12]
It is possible for a user to install just the SmartApp, go through the config steps and get a positive confirmation. However, the install will actually fail if the device types are not installed first. 

Need to update the app to return an error instead of a success popup

**Comment by ncsufire** [comment]
I was looking at Bruce's Rule Machine where you need to have Rule installed to operate properly.  I looked through the code and while I do not think you need all of this I think you can use this similar code to make it work.  Hope this helps.

def mainPage() {
    dynamicPage(name: "mainPage", title: "Installed Rules", install: true, uninstall: false, submitOnChange: true) {
        if(!state.setup) initialize(true)
        section {
            app(name: "childRules", appName: "Rule", namespace: "bravenel", title: "Create New Rule...", multiple: true)
        }
}
def installed() {
    if(!state.setup) initialize(true) else initialize(false)
}
def updated() {
    initialize(false)
}

**Comment by StrykerSKS** [comment]
Thanks @ncsufire I'll take a look to see if it is something I can use or not. What I'm also going to need though is someway to detect if a particular device type is installed or not.

**Comment by StrykerSKS** [comment]
The latest version now performs a check to make sure that the device handlers have been installed. It does this by creating a dummy device which is then later deleted as part of the install.
