### ISSUE TITLE
Weather Forecast not working

### ISSUE THREAD

**Issue by snakedog116** [StrykerSKS/SmartThingsPublic#13]
Not sure if my geographical location is the issue (perhaps the smart app only works in the US?) but my ecobee3 can tell me that it's cloudy, or going to rain etc, but the SmartThings app seems to only ever display that it is "updating".

See screenshot below

> ![img_4677 - copy](https://cloud.githubusercontent.com/assets/15080795/12202641/2764928e-b5e8-11e5-9f5c-bc18d2b28441.PNG)

**Comment by StrykerSKS** [comment]
The SmartApp gets the weather info via the Ecobee API. Ecobee returns a number which represents the forecasted weather. 

Can you check your Live logs to see what weatherSymbol is being returned by the API?

**Comment by snakedog116** [comment]
Looks like -2?

> temperature: 18
> humidity: 28
> heatingSetpoint: 18
> coolingSetpoint: 27
> thermostatSetpoint: 18
> thermostatMode: heat
> thermostatOperatingState: idle
> temperatureScale: C
> thermostatStatus: Right Now: Idle
> apiConnected: true
> weatherSymbol: -2

**Comment by snakedog116** [comment]
When I press on weatherSymbol it tells me the following. Looks like this is close to a week old?

Date    Name    Value   Units
2016-01-04 8:41 PM UTC - 6 days ago weatherSymbol   -2

**Comment by ncsufire** [comment]
Mine has been pretty consistent with the Ecobee3 app.

**Comment by StrykerSKS** [comment]
Well, if the data point doesn't change then SmartThings doesn't update the tile. So it would cause it to look old.

the more troubling part is that it seems that the API is only returning -2. To be sure, can you did a bit deeper for me?
- Go to the ST IDE
- Click on `My Locations`
- Scroll all the way down and Click on `List SmartApps`
- Click on `Ecobee (Connect)`
- Search for `weatherSymbol` in the screen, specifically looking for matches inside `thermostatData`

This is th eraw data that is captured from the API. If it is `-2` there then this is what Ecobee is sending over to us when we query. Not sure why they would do that if they are able to deliver the weather info to your actual thermostat. 

If it is returning `-2` in the raw data then we'll likely have to open a trouble ticket with Ecobee.

**Comment by snakedog116** [comment]
I see weatherSymbol several times in both thermostatData and thermostat.

Not sure which one I should be looking at.

**thermostatData**

> {status={message=, code=0}, page={total=1, page=1, pageSize=1, totalPages=1}, thermostatList=[{lastModified=2016-01-10 20:33:46, settings={serviceRemindMe=false, stage1CoolingDifferentialTemp=5, dehumidifierLevel=60, remindMeDate=2016-04-27, drAccept=always, disableHeatPumpAlerts=false, coldTempAlertEnabled=true, compressorProtectionMinTemp=350, hvacMode=heat, heatStages=2, dehumidifyWithAC=false, disablePreHeating=false, auxMaxOutdoorTemp=700, maxSetBack=100, humidityHighAlert=-1, backlightOnIntensity=10, humidifierMode=auto, humidity=26, dehumidifyWhenHeating=false, compressorProtectionMinTime=300, soundAlertVolume=0, heatMaxTemp=1200, ventilatorMinOnTime=20, installerCodeRequired=false, groupName=, hasHeatPump=false, holdAction=useEndTime2hour, backlightOffDuringSleep=false, hotTempAlertEnabled=true, humidityAlertNotifyTechnician=false, backlightSleepIntensity=3, randomStartDelayHeat=0, useCelsius=true, auxRuntimeAlertNotifyTechnician=false, stage1HeatingDissipationTime=31, smartCirculation=false, tempAlertNotifyTechnician=false, coolMaxTemp=1200, humidityLowAlert=20, humidityAlertNotify=true, autoAway=true, randomStartDelayCool=0, vent=off, heatPumpReversalOnCool=true, fanControlRequired=true, soundTickVolume=0, isRentalProperty=false, hasForcedAir=true, useZoneController=false, ventilatorDehumidify=true, fanMinOnTime=5, dehumidifyOvercoolOffset=0, heatMinTemp=450, quickSaveSetBack=40, stage1HeatingDifferentialTemp=5, hasBoiler=false, coolRangeHigh=920, backlightOffTime=60, auxOutdoorTempAlertNotifyTechnician=false, hasUVFilter=true, eiLocation=, quickSaveSetForward=40, hasErv=false, heatRangeLow=590, disableAlertsOnIdt=false, coolMinTemp=-100, ventilatorMinOnTimeHome=20, coolingLockout=false, auxOutdoorTempAlert=500, stage1CoolingDissipationTime=31, enableElectricityBillAlert=false, followMeComfort=true, lastServiceDate=2015-10-27, condensationAvoid=false, groupRef=, auxOutdoorTempAlertNotify=false, electricityBillStartMonth=1, ventilatorOffDateTime=, hasElectric=false, autoHeatCoolFeatureEnabled=false, monthsBetweenService=6, locale=en, ventilatorFreeCooling=true, heatRangeHigh=752, serviceRemindTechnician=false, ventilatorType=none, tempCorrection=0, heatCoolMinDelta=50, ventilatorMinOnTimeAway=0, userAccessSetting=0, useTimeFormat12=true, isVentilatorTimerOn=false, heatPumpGroundWater=false, auxRuntimeAlertNotify=false, groupSetting=0, monthlyElectricityBillLimit=0, maxSetForward=80, coolRangeLow=650, electricityBillingDayOfMonth=1, wifiOfflineAlert=false, electricityBillCycleMonths=1, hotTempAlert=770, hasHrv=false, dehumidifierMode=off, disablePreCooling=false, coldTempAlert=590, hasDehumidifier=false, coolStages=0, hasHumidifier=true, userAccessCode=, enableProjectedElectricityBillAlert=false, auxRuntimeAlert=10800, tempAlertNotify=true}, runtime={lastModified=2016-01-10 23:55:58, connected=true, desiredHumidity=26, desiredHeat=707, connectDateTime=2016-01-10 10:34:06, runtimeInterval=285, actualHumidity=33, actualTemperature=708, firstConnected=2015-10-27 23:42:18, disconnectDateTime=2016-01-10 08:11:13, runtimeDate=2016-01-10, desiredFanMode=auto, lastStatusModified=2016-01-10 23:55:58, runtimeRev=160110235558, desiredCool=779, desiredDehumidity=60}, isRegistered=true, remoteSensors=[{id=rs:102, inUse=true, name=Office, code=F378, type=ecobee3_remote_sensor, capability=[{id=1, value=717, type=temperature}, {id=2, value=true, type=occupancy}]}, {id=rs:100, inUse=true, name=Family Room, code=FZZV, type=ecobee3_remote_sensor, capability=[{id=1, value=712, type=temperature}, {id=2, value=true, type=occupancy}]}, {id=rs:101, inUse=true, name=Bedroom, code=F37H, type=ecobee3_remote_sensor, capability=[{id=1, value=708, type=temperature}, {id=2, value=true, type=occupancy}]}, {id=ei:0, inUse=true, name=My ecobee3, type=thermostat, capability=[{id=1, value=703, type=temperature}, {id=2, value=33, type=humidity}, {id=3, value=true, type=occupancy}]}], thermostatRev=160110203346, name=My ecobee3, features=HomeKit, weather={timestamp=2016-01-10 23:43:32, forecasts=[{windGust=-5002, pressure=1019, relativeHumidity=75, weatherSymbol=-2, dateTime=2016-01-10 16:27:07, condition=Chilly., visibility=-5002, windDirection=W, tempLow=-34, tempHigh=251, pop=5, temperature=279, windSpeed=7000, sky=-5002, windBearing=270, dewpoint=216}, {windGust=-5002, pressure=1024, relativeHumidity=84, weatherSymbol=3, dateTime=2016-01-11 16:27:07, condition=Mostly cloudy. Chilly., visibility=-5002, windDirection=SE, tempLow=82, tempHigh=203, pop=15, temperature=142, windSpeed=3000, sky=16, windBearing=147, dewpoint=75}, {windGust=-5002, pressure=1009, relativeHumidity=85, weatherSymbol=1, dateTime=2016-01-12 16:27:07, condition=More sun than clouds. Cool., visibility=-5002, windDirection=W, tempLow=96, tempHigh=287, pop=0, temperature=191, windSpeed=9000, sky=8, windBearing=249, dewpoint=217}, {windGust=-5002, pressure=1000, relativeHumidity=85, weatherSymbol=3, dateTime=2016-01-13 16:27:07, condition=More clouds than sun. Cool., visibility=-5002, windDirection=SW, tempLow=143, tempHigh=260, pop=5, temperature=201, windSpeed=2000, sky=13, windBearing=217, dewpoint=191}, {windGust=-5002, pressure=1010, relativeHumidity=87, weatherSymbol=3, dateTime=2016-01-14 16:27:07, condition=Mostly cloudy. Chilly., visibility=-5002, windDirection=N, tempLow=95, tempHigh=212, pop=15, temperature=153, windSpeed=5000, sky=16, windBearing=22, dewpoint=142}, {windGust=-5002, pressure=-5002, relativeHumidity=87, weatherSymbol=3, dateTime=2016-01-10 14:00:00, condition=More clouds than sun. Cool., visibility=5000, windDirection=NW, tempLow=-5002, tempHigh=-5002, pop=5, temperature=251, windSpeed=9000, sky=13, windBearing=301, dewpoint=217}, {windGust=-5002, pressure=-5002, relativeHumidity=87, weatherSymbol=3, dateTime=2016-01-10 20:00:00, condition=Cloudy. Chilly., visibility=5000, windDirection=NW, tempLow=-5002, tempHigh=-5002, pop=15, temperature=212, windSpeed=7000, sky=17, windBearing=296, dewpoint=177}, {windGust=-5002, pressure=-5002, relativeHumidity=88, weatherSymbol=3, dateTime=2016-01-11 02:00:00, condition=Mostly cloudy. Chilly., visibility=4000, windDirection=NW, tempLow=-5002, tempHigh=-5002, pop=15, temperature=190, windSpeed=6000, sky=16, windBearing=329, dewpoint=161}, {windGust=-5002, pressure=-5002, relativeHumidity=75, weatherSymbol=3, dateTime=2016-01-11 08:00:00, condition=Mostly cloudy. Chilly., visibility=4000, windDirection=N, tempLow=-5002, tempHigh=-5002, pop=15, temperature=165, windSpeed=6000, sky=16, windBearing=12, dewpoint=100}], weatherStation=CW:54333}, brand=ecobee, utcTime=2016-01-10 23:57:52, equipmentStatus=, identifier=311078359667, modelNumber=athenaSmart, thermostatTime=2016-01-10 16:57:52}]}

**thermostat**

> {e5e17170-108e-4e7f-ab6e-df903511e945.311078359667={data={heatingSetpoint=22, temperatureScale=C, humidity=33, apiConnected=true, weatherTemperature=-2, heatMode=true, weatherSymbol=-2, thermostatMode=heat, autoMode=false, coolingSetpoint=26, thermostatOperatingState=idle, coolMode=false, auxHeatMode=false, temperature=22}}}

**Comment by snakedog116** [comment]
I'm starting to wonder if it's the ecobee, the weather forecast seems ok, but the current weather has an unhappy cloud. I thought that was because the weather isn't nice, but perhaps that's an error? It's been an unhappy cloud for several days.

I've reached out to Ecobee tech support.

**Comment by ncsufire** [comment]
I believe the unhappy cloud on the Ecobee is that it doesn't have
connection either to the internet or their servers.

Try to log back into the Ecobee website and verify your location is correct.

**Comment by snakedog116** [comment]
Yea, turns out it means no weather... which is stupid, but not your issue, this is Ecobee's... I'm not in a tiny town in the boonies... It's a large enough city, just I guess I'm north of the boarder and so Ecobee doesn't figure I want to know the weather? Anyways, this isn't an issue with Stryker's code. It's Ecobee's issue.

https://ecobee.zendesk.com/entries/62590440-ecobee3-thermostat-icons-what-do-they-mean-

**Comment by StrykerSKS** [comment]
The strange part is that it shows weather for future dates, just not **today**. Notice that the forecast values for other days have something other than "-2". Definitely seems likely something on the Ecobee side. 

But that link is awesome! I might be able to use it to do custom icons at some point in the (likely distant) future!

**Comment by snakedog116** [comment]
Yes, it is strange. I have the unhappy cloud only on the current weather on the Ecobee as well, the forecast works fine.
