### ISSUE TITLE
Thermostat Motion information is not reported

### ISSUE THREAD

**Issue by StrykerSKS** [StrykerSKS/SmartThingsPublic#14]
The motion/occupancy information for the thermostat is not currently captured and reported.

Need to decide if I:
- use the Ecobee Sensor device type to capture this
- expose the info as part of the thermostat device type

Pros and Cons with each method, but as long as we use the same Capabilities type for each then they would behave the same way.

**Comment by snakedog116** [comment]
I would prefer to see it within the Thermostat device. But I guess it isn't too big of a deal.

Having a second device would just confuse things (Which temperature do I use, the thermostat, or the thermostat sensor? etc.)

But that's just my 2 cents.

I understand why the thermostat is a presence sensor (the Ecobee doesn't say "motion" "Stop Motion" like a motion sensor does. It really just says that the room is occupied or not (I thought I read it's a 30 minute sampling period? If it's seen motion in the last 30 minutes it says the room is occupied?) But in my opinion I'd like to see all the sensors and the Ecobee all act as 'motion' not 'presence'.

**Comment by loverso** [comment]
https://www.ecobee.com/home/developer/api/documentation/v1/objects/RemoteSensor.shtml
"The remote sensor data will only show computed occupancy, as does the thermostat. Definition - For a given sensor, computed occupancy means a sensor is occupied if any motion was detected in the past 30 minutes."

**Comment by snakedog116** [comment]
There you go, see I knew I read that somewhere. Anyways, it's odd that the current code for the Ecobee is set as a presence sensor, while the sensors are motion sensors... that should be made consistent.

**Comment by StrykerSKS** [comment]
From what I've seen, the motion activated occurs pretty quickly (minutes, not realtime) and then once activated it stays activated for a while. I haven't timed it yet, but 30 minutes is probably right. So these can't be used for "real time" motion sensing, but are an okay choice to trigger things related to if a room is in use (such as smart vents, ceiling fans, etc) that don't need realtime. 

I agree that it doesn't make sense to have one as presence and the other as motion. I'll probably make them both just motion, just need to think through if there are impacts on any usecases where people want to automate certain steps (don't think there are).

**Comment by StrykerSKS** [comment]
Okay, have now added support for Motion on the thermostat including the thermostat tile.

I went ahead and pushed it to both the Beta (StrykerSKS-enhanced-ecobee) and main (StrykerSKS-Ecobee3) branches since it was a relatively small change.
