### ISSUE TITLE
Expose internal temp sensor in Ecobee3 thermostat

### ISSUE THREAD

**Issue by Roadrider** [StrykerSKS/SmartThingsPublic#15]
Expose the internal temp sensor in Ecobee3 t-stat for use in controlling smart vents.

**Comment by snakedog116** [comment]
claytonjn
CLAYTON
19h
Would it make sense/be possible to have the thermostat/sensors be in one device handler which shows temperature and motion, and have another device handler which is more of a "system" device with the average temperature and the actual controls of mode/temperature settings/climate/etc. Does this make sense?

**Comment by ncsufire** [comment]
This appears to be the case already; on my system the average temperature currently is 69F but on the ST app my downstairs thermostat temperature is reading 68F which is confirmed when I look at my sensors.  

I am not sure if this is a rounding error with the application or something Stryker needs to take a look at.

**Comment by ncsufire** [comment]
![1](https://cloud.githubusercontent.com/assets/16526555/12594077/34aa4750-c442-11e5-8312-5c4b1893dca9.JPG)
![2](https://cloud.githubusercontent.com/assets/16526555/12594076/34a16810-c442-11e5-8959-0d082f185bfa.JPG)
![screenshot_2016-01-26-15-32-33](https://cloud.githubusercontent.com/assets/16526555/12594075/34a0eb4c-c442-11e5-8b7a-0d9f04f3f43a.png)

**Comment by StrykerSKS** [comment]
I will need to double check, but I'm pretty sure that the value I'm referencing in the API is the average temperature. I have not done anything yet to extract the actual temperature which resides in the sensors list. 

This _may_ be a rounding situation, or it could just be a timing issue. The thermostat has real-time information, I only have what is available in the cloud. Plus there is a lag from a polling perspective. While the display only shows whole numbers, everything is actually stored in decimal values on the backend.

**Comment by StrykerSKS** [comment]
Implemented in latest version including the v0.9.0 beta releases
