### ISSUE TITLE
ecobee (Connect) does not complete (with Smart Si)

### ISSUE THREAD

**Issue by ghost** [StrykerSKS/SmartThingsPublic#16]
When running ecobee (Connect) with ecobee Smart Si the app gets "encountered an unexpected error."  This occurs in the select senors phase.  Note the Smart Si doesn't have a presence sensor capability. Once the error is encountered the Select Sensor process loop continues without end.

**Comment by natalan** [comment]
+1. I am experiencing the same issue

**Comment by StrykerSKS** [comment]
@natalan Just to be sure, you are also using a Smart Si?

**Comment by natalan** [comment]
@StrykerSKS yes, it's SmartSi. I had to revert back to abbaeeac669cfcde5b7c6070fd4b42d1c2aa6f46 and Connect works again

**Comment by StrykerSKS** [comment]
Okay, the plot thickens. Didn't realize that it used to work but then stopped!

This helps since I can then see what I've changed that may have broken things!

**Comment by StrykerSKS** [comment]
Started looking at the change history. I did make some changes to the Thermostat device type to add the motion capability which might be part of the problem.

When you last updated the SmartApp, did you also update the Device Types to the same version?

**Comment by natalan** [comment]
@StrykerSKS yes, I updated both SmartApp and Device Type (only thermostat as SmartSi doesn't support sensors) to the latest version and it didn't work because of the motion capability:
There was an error thrown at this line https://github.com/StrykerSKS/SmartThingsPublic/blob/StrykerSKS-Ecobee3/smartapps/smartthings/ecobee-connect.src/ecobee-connect.groovy#L832 Something like `Cannot read capability of null` if I recall correctly.

Now, I have the SmartApp at abbaeeac669cfcde5b7c6070fd4b42d1c2aa6f46 (the one before motion capability change) and still the latest Device Type and things seem to work fine.

**Comment by ghost** [comment]
I was able to get the latest version of SmartApp working without any Device Type (Handler) changes.  In the Connect app I commented out lines 832 and 833.  Then I changed line 836 to
def occupancy = 0

**Comment by StrykerSKS** [comment]
Thanks, that helps. I will add some checks in the next version for null values and hopefully will be able to handle both cases.

**Comment by harleychevy** [comment]
My smart SI connected through the app now but it doesnt update and if you click it on the smartthings app it crashes the app. My ecobee 3 and remote sensor work great.

**Comment by StrykerSKS** [comment]
Adding log entries from community site to help track:

025f3591-be53-441c-b71b-5b4ed5964497 7:47:16 AM CST: debug getChildDevices(true), children=5
025f3591-be53-441c-b71b-5b4ed5964497 7:47:16 AM CST: debug LOG: created EcoSensor: null with id living room
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: debug LOG: Created/Updated 1 thermostats
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: debug LOG: createChildrenSensors() entered: ecobeesensors=[master, living room, ecobee_sensor-rs:0:2-null, ecobee_sensor-rs:0:1-null]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: debug LOG: found Ecobee Thermostat with id 025f3591-be53-441c-b71b-5b4ed5964497.198779613267 already exists
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: debug LOG: createChildrenThermostats() entered: thermostats=[025f3591-be53-441c-b71b-5b4ed5964497.198779613267]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: debug LOG: getEcobeeSensors() - remote sensor list: [:]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Did NOT add: [id:rs:0:4, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]. settings.showThermsAsSensor=true
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Did NOT add: [id:rs:0:3, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]. settings.showThermsAsSensor=true
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Looping through each remoteSensor. Current remoteSensor: [id:rs:0:4, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Did NOT add: [id:rs:20:0, inUse:false, name:Plug , type:monitor_sensor, capability:[[id:, value:0, type:plug]]]. settings.showThermsAsSensor=true
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Looping through each remoteSensor. Current remoteSensor: [id:rs:0:3, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Looping through each remoteSensor. Current remoteSensor: [id:ei:0:2, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Did NOT add: [id:ei:0:2, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]. settings.showThermsAsSensor=true
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Looping through each remoteSensor. Current remoteSensor: [id:rs:0:1, inUse:true, name:living, type:control_sensor, capability:[[id:, value:638, type:temperature]]]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Did NOT add: [id:ei:0:1, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]. settings.showThermsAsSensor=true
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Looping through each remoteSensor. Current remoteSensor: [id:ei:0:1, inUse:false, name:, type:monitor_sensor, capability:[[id:, value:0, type:dryContact]]]
025f3591-be53-441c-b71b-5b4ed5964497 7:47:15 AM CST: trace LOG: Did NOT add: [id:rs:0:2, inUse:true, name:master, type:control_sensor, capability:[[id:, value:671, type:temperature]]].

**Comment by StrykerSKS** [comment]
Just a quick update since several people are waiting for this. I am working with someone that has a Smart SI unit to work through this. We have made some progress over the last few days. I'm hoping that we will make a breakthrough soon (perhaps today even).

If anyone wants to also test and provide logs/feedback, you can use the Ecobee (Connect) code on the StrykerSKS-ecobee-smartsi branch (https://github.com/StrykerSKS/SmartThingsPublic/tree/StrykerSKS-ecobee-smartsi)
