### ISSUE TITLE
Add version number inside Ecobee (Connect) app to make it easier to know which version is running

### ISSUE THREAD

**Issue by StrykerSKS** [StrykerSKS/SmartThingsPublic#19]
Given all the rapid development it is hard to know if everything was updated properly, so it would be good to display the version number of the SmartApp from within the app itself. This will make it much easier to troubleshoot for users!

**Comment by ncsufire** [comment]
You may be able to accomplish this by looking at how Bruce displays the information on Rule Machine; he displays the version of Rule Machine and Rule in the app.

**Comment by StrykerSKS** [comment]
App version now included in the app.
