### ISSUE TITLE
Using mode to set ecobee3 program

### ISSUE THREAD

**Issue by rickybloomfield** [StrykerSKS/SmartThingsPublic#25]
There may be an issue with using the SmartThings mode to set the ecobee3 program. I have things set up per the attached screenshot, expecting that when the SmartThings mode is set to "Away" my ecobee3 program will be set to "Away" automatically (I have another that should be set to "Resume" when mode set to "Home"). But it's not working.

Related to this, if this is the behavior I should be expecting (I'm not sure it is ...), it would be helpful to rename the options to something like:

"When mode switches to:"
_mode_
"Set Program to:"
_program_

![img_4106](https://cloud.githubusercontent.com/assets/868473/12869186/8d0a16fe-cce5-11e5-8910-7dbceabd781d.PNG)

**Comment by StrykerSKS** [comment]
I really like the suggestion on renaming the sections to make it more clear.

On the actual problem you are having, though, I'm not able to reproduce it. I just setup the exact same rule. Manually executed my Goodbye routine and then waited for the thermostat to update. Everything worked as expected on my end. 

And then for good measure, I have the "I'm Back" routine setup to resume my program and that worked as well. 

What version of the Ecobee (Connect) and ecobee Routines SmartApps are you using? (Listed on the first page of each SmartApp)

**Comment by rickybloomfield** [comment]
Thanks. I'm using the latest - I just updated from the repo (v. 0.9.1-RC6 & 0.1.0-RC5).

Interestingly, I'm seeing it work when I resume, but not when set away (which is why it seemed like nothing happened ...). See attached screenshots. Unclear why this is the case.

![img_4108](https://cloud.githubusercontent.com/assets/868473/12869727/87afbb04-ccf5-11e5-87b7-6245859fbe8d.PNG)

![img_4109](https://cloud.githubusercontent.com/assets/868473/12869728/87bd5ade-ccf5-11e5-99fe-407a5dda97e2.PNG)

**Comment by StrykerSKS** [comment]
I see multiple Goodbye! commands, but that won't help if you are already in Goodbye! mode.

Were you physically observing the thermostat to see if it changed? (either standing in front of it or using ecobee.com)? 

I am not sure what determines what goes in the Activity Feed or not.

**Comment by rickybloomfield** [comment]
Yeah, I have no idea why there are so many Goodbye! commands - it's always done that. I assume that it's for each light/switch I ask it to turn off. In fact, I just looked, and there are 7 lights/switches and 7 additional "Goodbye!" commands, so that must be it. But that should be totally unrelated to the ecobee3 setup.

I was standing in front of the ecobee3 and nothing happened there, either. Strange.

**Comment by StrykerSKS** [comment]
Okay, What happens when you press the "Set Away" button on the Thermostat Thing? Does the button work? If that doesn't work then there is an issue with the SmartApp (Connect) somewhere.

**Comment by rickybloomfield** [comment]
Hmmm ... on the device view itself? I don't have a "Set Away" button there. I actually just have a "Resume" button even though it's not in "Away" mode:

![img_4110](https://cloud.githubusercontent.com/assets/868473/12870316/47f6071c-cd0d-11e5-8e88-305485582e06.jpg)

**Comment by rickybloomfield** [comment]
Just a thought - I have an ecobee3 with HomeKit enabled. One of the side effects of that is that "Auto" mode is not supported, just Heat, Cool, or Off. Could that have an effect on this at all? An upcoming firmware update will add back "Auto" but I don't have it, yet.

**Comment by StrykerSKS** [comment]
Not even if you scroll down?? Look at the screenshot below. If you don't have those buttons then you don't have the latest version of the Thermostat Device Handler, in which case those features won't work.

The "Auto" function shouldn't have any impact on setting "Home", "Away" and "Sleep" Programs.

![photo feb 03 2 06 33 am](https://cloud.githubusercontent.com/assets/14816593/12870734/0db06d44-cd18-11e5-9853-73bd44aaebc7.png)

**Comment by rickybloomfield** [comment]
That was it. I thought that when I pulled the Git updates the device handler was updated as well - I was wrong. Sorry for the false alarm! Closing this. It works great - thanks so much for this!

**Comment by StrykerSKS** [comment]
Prefer a false alarm over a bug any time!

Note for anyone else who comes across this. In the SmartThings IDE updating the SmartApp doesn't update the devices (unfortunately). It takes two steps.
