### ISSUE TITLE
Thermostat Mode of Operation

### ISSUE THREAD

**Issue by ncsufire** [StrykerSKS/SmartThingsPublic#4]
Clicking on the bottom right tile where you change the modes should open a new window to select the mode.  When I click from 'Auto' it wants to immediately enter my thermostat into 'Emergency Heat'

**Comment by StrykerSKS** [comment]
This is a limitation in the way that "Tiles" work within SmartThings. I'm not aware of a tile option that would give a popup and allow for a selection of items. All you can do is perform an "action" when a tile is clicked and then change the state of that tile.

So in this case, when you click on the mode tile, it calls a function called "switchMode" that cycles through the different available modes. So to get to the mode that you want you have to click the tile several times. 

You can read up on tiles and their options [here](http://docs.smartthings.com/en/latest/device-type-developers-guide/tiles-metadata.html).

And if you want an example of another thermostat that also does it this way, check out the [Zen Thermostat](https://github.com/StrykerSKS/SmartThingsPublic/blob/StrykerSKS-enhanced-ecobeedevice/devicetypes/zenwithin/zen-thermostat.src/zen-thermostat.groovy).
