### ISSUE TITLE
Heat and Cool Sliders Hard to use

### ISSUE THREAD

**Issue by snakedog116** [StrykerSKS/SmartThingsPublic#6]
Anyone else having issues with the Heat and Cool Sliders? It seems to me that a height of 1 is too small to grab the slider easily.

I've adjusted my code to a height of 2 and that makes a world of difference.

(I'm using an iPhone 5s, not sure if a bigger phone would make a height of 1 work better?)

I've sent in a ticket to SmartThings, because they should fix the sliders with a height of 1, but for now, could we have this set to a height of 2?

**Comment by StrykerSKS** [comment]
I'm on a plane right now but will play with it tonight. I'm on an iPhone 6 and haven't had any problems with it so far. I actually have enjoyed the granularity of the slider. 

Let me see how height 2 looks, trying to avoid taking up too much room if possible. There are more attributes/features that I want to add so it will become very cluttered if things are too big.

**Comment by snakedog116** [comment]
Oh, I hear you. Height of 1 looks much better, but honestly it's mostly not usable on my phone. I can't grab the slider without multiple tries.

**Comment by StrykerSKS** [comment]
So I experimented with height: 1 and height: 2. From my testing it seems that the actual slider and "knob"  were exactly the same size. The only thing that seemed to change was the whitespace around the slider. 

From testing I didn't see any improvement in my ability to grab the "knob" I found that I usually missed the first time with either configuration and had to try again. 

So probably still worth opening a ticket with ST to get them to improve the handling.

**Comment by snakedog116** [comment]
You are right that the actual knob doesn't change size, but it seems like the area you can grab changes significantly.

Is anyone else using an iphone 5s, or smaller? is this an issue for you as well?

I have emailed SmartThings tech support.

**Comment by ncsufire** [comment]
I have Android Galaxy S5.  It is not hard to grab  the slider but when I do the temperature jumps significantly and I have to slowly bring it back.  I think that ease of use is probably directly correlated to thumb size :)

**Comment by snakedog116** [comment]
The Galaxy 5s is larger than the iphone 5s. I should video myself trying to use the slider...

**Comment by snakedog116** [comment]
I spoke with SmartThings' tech support. They said it's a known issue with the smaller iphone screens.

It would be nice to have a height of 2, but this is a SmartThings' bug and no one else is complaining about your sliders. So I've closed this issue. (I may just increase the height on my end once the coding calms down and @StrykerSKS isn't pushing new code so frequently!)
