### ISSUE TITLE
Exposing vent feature

### ISSUE THREAD

**Issue by colin1497** [StrykerSKS/SmartThingsPublic#62]
I'm just digging through the API.  I see your issue you're having with fan.  I'm not sure, but does settings.vent turn the fan on with the ventilator?

I'd like to expose settings.vent, tied to turning the fan on.  This would allow setting up rules that would turn the ventilator on.

That said, could this be a crutch for cycling the fan?  Probably not if no ventilator is configured...

**Comment by StrykerSKS** [comment]
The Ecobee APIs do not support controlling a ventilator unfortunately. 

See this discussion on the Ecobee Developer Forum for example:
http://developer.ecobee.com/api/topics/not-able-to-control-the-ventilator-from-the-apis

(There are other threads, I just grabbed the first one.)
