### ISSUE TITLE
Smartapp didn't catch API disconnect

### ISSUE THREAD

**Issue by mattsch** [StrykerSKS/SmartThingsPublic#63]
Noticed this morning that the thermostat display wasn't updating on my phone, checked the logs and saw a bunch of these 400 errors logged when the app was trying to refresh:
`error refreshAuthToken() - HttpResponseException occured. Exception info: groovyx.net.http.HttpResponseException: Bad Request StatusCode: 400`

I re-authorized and everything is working well now, but this likely should get flagged as an even required a re-auth notification.

**Comment by StrykerSKS** [comment]
Usually this is a recoverable error and caused by something on the server side. As you noted, sometimes it never recovers. 

I'll look into making it a little more proactive about flagging in this scenario.
