### ISSUE TITLE
Operating Tile Overlap of Text

### ISSUE THREAD

**Issue by ncsufire** [StrykerSKS/SmartThingsPublic#7]
Here are the screen shots of the Operating Tile and the overlap and then the Fan Only.  Here is what was happening.  The thermostat was running in heat mote.  My thermostat is setup such that when the Heat (or A/C) turns off the fan will run for 30 or so seconds to blow the remaining hot (or cold) air from the ducts into the house.  As soon as I heard the thermostat click off I refreshed the thermostat in the Smart Apps and got this:
![screenshot 1](https://cloud.githubusercontent.com/assets/16526555/12132750/f8395172-b3ec-11e5-8c43-58f9fabe8a55.png)
After 20 or so seconds I refreshed and got this:
![screenshot 2](https://cloud.githubusercontent.com/assets/16526555/12132754/05321f58-b3ed-11e5-8ef2-55bbb3f4d048.png)
Here is the log of events from Recent
![events](https://cloud.githubusercontent.com/assets/16526555/12132761/11b55d1c-b3ed-11e5-9b37-56379660f4ed.png)

**Comment by StrykerSKS** [comment]
I think I may have this fixed now, can you please test with the latest software version (update all 3 files) and report back?

**Comment by ncsufire** [comment]
It appears to be working.  One thing I noticed while testing is that when I hit refresh sometimes it does not do anything, could that be because there is not state change?  For the purpose of this issue I believe we can close it.

**Comment by StrykerSKS** [comment]
Yes, if there hasn't been anything that changed then you likely won't see it "do" anything. You can verify that the refresh command was sent by looking in the Recently tab. It should show the refresh command in there when it is issued.

**Comment by ncsufire** [comment]
My last entry in the Recently tab was 5:41 pm.  When I hit refresh in the thermostat it didn't show up in the Recently tab but it does show up in the Live Log.
