### ISSUE TITLE
Issue: Open Contacts will not save via Android

### ISSUE THREAD

**Issue by neonguyrt** [StrykerSKS/SmartThingsPublic#71]
Tried saving the open contacts on my Samsung Galaxy Note 5 and I receive "an unexpected error has occurred" when pressing "done" to save the smartapp.
Phone: Verizon Samsung Galaxy Note 5 (Samsung-SM-N920V)
Android Version 6.0.1

**Comment by StrykerSKS** [comment]
Investigating

**Comment by neonguyrt** [comment]
If you need an android system to test with, you can download eclipse and android SDK. Then you can use android simulator. LMK if you need anything from me. Thanks!

**Comment by StrykerSKS** [comment]
Thanks, I have access to a Galaxy S7 Edge that I'm testing on. So far I'm unable to reproduce this issue though. I'm updating the SmartThings app to see if perhaps something broke in the most recent version.

In the meantime, can you ensure that you have the latest versions of all the Ecobee components? (Connect, Thermostat, Routines, etc)

**Comment by neonguyrt** [comment]
I used the github method and pulled from here.

**Comment by neonguyrt** [comment]
![screenshot_20160912-133015](https://cloud.githubusercontent.com/assets/22054943/18445852/86b566a0-78ed-11e6-930b-212eee9cb732.png)

**Comment by neonguyrt** [comment]
Any way I can pull the logs from my phone and send to you? Need some help how to get them but willing to!

**Comment by StrykerSKS** [comment]
Not sure how to pull logs from the phone, but you CAN pull up the live logging from the SmartThings IDE (graph.api.smartthings.com/ide/apps). Just be sure to have the Ecobee (Connect) set to debug level 3 or higher (with 5 giving the most information). 

My Android test phone won't let me install the SmartThings app for some unknown reason, so I'm still fighting with t hat.

**Comment by neonguyrt** [comment]
4f755360-b876-4ec9-aef6-da25567c7242  12:17:01 PM: error groovy.lang.MissingMethodException: No signature of method: script1473925347184369487434.LOG() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl, java.lang.Integer, null, java.lang.String, java.lang.Boolean, java.lang.Boolean) values: [Test installed() entered, 5, null, debug, ...]
Possible solutions: now(), url(), run(), any(), page(), poll() @ line 312

**Comment by StrykerSKS** [comment]
Can you confirm which module that error came out of? (4f755360-b876-4ec9-aef6-da25567c7242)

I'm assuming it is Open Contacts app that gave that error but that doesn't really make sense why it would do that. 

Are you trying to run the SmartApp standalone perhaps? Or are you creating it from within the Ecobee (Connect) SmartApp? 

This is a Child SmartApp that you need to create from within the Ecobee (Connect) SmartApp

**Comment by neonguyrt** [comment]
Standalone smart app ecobee open contacts.

-------- Original message --------

**Comment by StrykerSKS** [comment]
This is NOT a standalone SmartApp, you HAVE to run it from the Ecobee (Connect) app per the instructions in the README file.

**Comment by neonguyrt** [comment]
I do not have the option to run this from ecobee connect. Once I select the ecobee and the sensor it says it's connected and returns me to home page.

-------- Original message --------

**Comment by StrykerSKS** [comment]
Click on Automations --> SmartApps --> Ecobee (Connect)

Then select Helper SmartApps.

From there you can create an ecobee Routines or ecobee Open Contacts child SmartApp.

**Comment by neonguyrt** [comment]
No Helper Smartapps. This is all I have when selecting ecobee connect...
![screenshot_20160917-221043](https://cloud.githubusercontent.com/assets/22054943/18612280/b68dcc20-7d23-11e6-8647-44ad0bde5f4e.png)

**Comment by StrykerSKS** [comment]
Then you aren't using MY Ecobee (Connect) code, you must be using the stock Ecobee connect from SmartThings.

**Comment by neonguyrt** [comment]
Pretty sure I am.
![image](https://cloud.githubusercontent.com/assets/22054943/18612348/744d7160-7d25-11e6-88f3-54f0af322208.png)

**Comment by StrykerSKS** [comment]
Nope, not possible. There is not code in mine that would possibly create the screenshot that you presented. Even the ability to Remove the SmartApp is one layer deeper in my version.

I suspect that you installed the code in the IDE, but when you went into the Marketplace to install you did not use the My Apps option and instead selected from the normal path. 

Only other option is that SmartThings has changed something on their backend that would cause their app to override mine since they are in the same namespace. 

To check, go into the IDE, click My Locations --> [Your location name] --> List SmartApps (scroll all the way down). Then find the Ecobee (Connect) app. It should have the word "(dev)" at the end to indicate that it is running a developer version. Click on it to open up the popup and there should be a host of settings, subscriptions, etc. 

Do you see these Settings: debugLevel, holdType, showThermsAsSensor?

If you don't see those then you are not running my code.

**Comment by neonguyrt** [comment]
How do I fix it then? Remove it and start over?
![image](https://cloud.githubusercontent.com/assets/22054943/18612427/8d7c47f4-7d27-11e6-95a5-9d58dd06e6c0.png)

**Comment by StrykerSKS** [comment]
Yup, not my code.

Suggest you remove the current SmartApp and reinstall using the My Apps section of the Marketplace

**Comment by neonguyrt** [comment]
ok, thx :)

**Comment by neonguyrt** [comment]
Thats what It was. I had installed Ecobee prior to finding this code and tried to modify it. I did not see directions to remove it or start as if the thermostat was not yet added. Thanks for the help!
