### ISSUE TITLE
Issue: Routines screen returns blank

### ISSUE THREAD

**Issue by neonguyrt** [StrykerSKS/SmartThingsPublic#72]
Tried selecting my ecobee thermostat on my Samsung Galaxy Note 5 and the screen returns blank only allowing me to back out of the app not saving it. If I select "Done" it says not all fields are filed out.
Phone: Verizon Samsung Galaxy Note 5 (Samsung-SM-N920V)
Android Version 6.0.1

**Comment by StrykerSKS** [comment]
Investigating

**Comment by StrykerSKS** [comment]
You MUST run this as a child app from the Ecobee (Connect) per the README instructions. This is NOT a standalone SmartApp
