### ISSUE TITLE
Error Saving Page on SmartApp Setup (No devices installed)

### ISSUE THREAD

**Issue by trb5016** [StrykerSKS/SmartThingsPublic#73]
After setting up the two device handlers, and the three SmartApps (Connect, Open Contacts, and Routines) on the IDE, I went to the app to install Ecobee (Connect), I am able to select the thermostat and sensor, however, when I click "Done" I get an "Error Saving Page" message, and no devices are installed in "Things".

I am on Android.  I have confirmed that OAuth is enabled under the "My SmartApps" tab in the IDE.  (I initially tried with just the connect app, then enabled for all three apps, but got the same result.)

Log attached:

[Ecobee (Connect) Log.txt](https://github.com/StrykerSKS/SmartThingsPublic/files/602486/Ecobee.Connect.Log.txt)

**Comment by StrykerSKS** [comment]
Just to confirm, what version of the code are you using? Did you use the GitHub install method (I assume so since you are posting here on GitHub). What branch are you using? (Should be StrykerSKS-Ecobee3).

Did you the initial saving of credentials work the first time before going into preferences to select the various individual devices?

Did you have a previous version setup before?

**Comment by trb5016** [comment]
Confirmed - used GitHub install method using the StrykerSKS-Ecobee3 branch.

Now that you mention it I think the credentials failed the first time.  (If I'm thinking of the right time, I did a lot of fiddling).  At first, I installed the official ST/Ecobee3 app.  I believe that set up/authenticated no problem.  I then uninstalled that, and went for your Ecobee (connect).  IIRC, It asked for the 1.) ecobee login (which worked) then it asked to log me in to SmartThings to approve it.  I entered my ST username/pw, and it gave *some* error.  I backed out, tried again and it worked.  Subsequent installs (after uninstalling your devices/smartapps) have not asked me to enter ST credentials, only the Ecobee3 ones.  (Caveat I might be mixing it up and this issue occured when I installed the official App for the first time).

I installed/uninstalled the official app, as well as your apps several times during fiddling.  I also installed a few of yracines smartapps before realizing the device handler itself was contribution only.  I *believe* I uninstalled everything -  My Devices/My SmartApps/My Device Handlers all show only your apps/handlers as I would expect, no ecobee stuff is showing under devices (hence the post.)  Other than that, this is a newly installed Ecobee3

P.S.  really appreciate the response.

**Comment by jimxenus** [comment]
It looks like I'm having the exact same problem. This is a brand new install having just installed my Ecobee3. I have no previous installs of any other device types or smart apps. I have tried removing the smartapp and reinstalling but that didn't help. I'm not sure if I know how to read the logs correctly but the error lines are below and I've attached my error log from live logging. I appreciate any help in this matter.

error refreshAuthToken(), General Exception: java.lang.NullPointerException: Cannot get property 'e2df9f75-86d1-4466-9fb9-bb05258c3ab5.311078443889' on null object.

error java.lang.NullPointerException: Cannot get property 'e2df9f75-86d1-4466-9fb9-bb05258c3ab5.311078443889' on null object @ line 1150

error pollEcobeeAPI(): General Exception: java.lang.NullPointerException: Cannot get property 'weatherSymbol' on null object.

[ecobee3 error log.txt](https://github.com/StrykerSKS/SmartThingsPublic/files/608001/ecobee3.error.log.txt)

**Comment by StrykerSKS** [comment]
I just tried a fresh install and got the same thing too. Something must have changed on the backend. I'll look at it sometime over this Thanksgiving break.

**Comment by jimxenus** [comment]
Thanks so much for the quick response. Don't work too hard over the break!

**Comment by StrykerSKS** [comment]
Can you try this again? I tried to reproduce but not seeing it now. (And the error I was having was related to me trying to do the install on a test hub that didn't have a location set, so not related to this error at all.)

**Comment by jimxenus** [comment]
Just tried it again without changing anything and this time, it worked! Thanks for taking the time to investigate. Must've been something going awry in the cloud.

**Comment by StrykerSKS** [comment]
Very relieved to hear that it worked for you!

It gets a bit frustrating trying to support an app when the underlying platform is so unstable at times.

**Comment by trb5016** [comment]
Apologies, I was away from home for a few days.  Wanted to let you know I was also able to get the app installed. Thanks for your support!

**Comment by Bboy486** [comment]
Sorry to bring up a closed ticket but I have the same issue. I opened a new ticket for it.
