### ISSUE TITLE
Changing Mode Erros

### ISSUE THREAD

**Issue by kylemcdonald87** [StrykerSKS/SmartThingsPublic#74]
I'm getting the following errors in Live Logging.  I've got a couple of smart apps set up to change on Routine that aren't working(as the log confirms).  I've also tried using Mode changes as well with the same result.

refreshAuthToken() - HttpResponseException occured. Exception info: groovyx.net.http.HttpResponseException: Bad Request StatusCode: 400

error sendJson() - HttpResponseException occured. Exception info: groovyx.net.http.HttpResponseException: Internal Server Error StatusCode: 500 response? data: 14

**Comment by StrykerSKS** [comment]
There was a SmartThings issue earlier. It can usually recover automatically but if it persists you will need to reauthenticate.

**Comment by kylemcdonald87** [comment]
Reauthenticate the connect smart app?

**Comment by StrykerSKS** [comment]
Yes, the Connect smartapp.

**Comment by kylemcdonald87** [comment]
Good deal. Working add expected. Thank ya
