### ISSUE TITLE
Climate (Comfort) Profiles

### ISSUE THREAD

**Issue by ncsufire** [StrykerSKS/SmartThingsPublic#8]
Enhancement request to add ability to change Ecobee3 comfort profile (Home, Away, Sleep).  Currently users can setup an IFTTT to change the comfort profile based upon a trigger.  Having the ability to change the profile through the app would allow users to use ST Rule Machine or other Apps on ST to change this status rather than using a third-party.

**Comment by snakedog116** [comment]
I second this request.

Ecobee calls these "Climates".
Some documentation is below for anyone who's wanting to give this a go:

https://www.ecobee.com/home/developer/api/documentation/v1/objects/Climate.shtml

**Comment by ncsufire** [comment]
Thanks @snakedog116 I was going off of the category in the Ecobee3 app.  I changed the header of the issue.

**Comment by StrykerSKS** [comment]
Looks like this shouldn't be that difficult in the grand scheme of things to add. The APIs make it possible to query for the list to get the reference IDs and then the setHold allows for using the reference to set the profile to use. 

Now just need to think about the best way to expose this. For this to be useful, I imagine we'd need to pass in which mode is wanted...

**Comment by lyonsad** [comment]
+1 on this one.  would be good to be able to hold at a certain profile or just until next scheduled one comes up.

**Comment by walksonair** [comment]
+1e6 on this as well. Great work, by the way. Thank you for keeping it Open Source.

**Comment by gazzer82** [comment]
+1 from me too, would love to be able to set away mode when everyone leaves rather than rely on the smart away in the ecobee or use IFTTT.

Thanks for you work so far, big improvement over the previous implementation!

**Comment by StrykerSKS** [comment]
Question for all of you. Would supporting the built-in 3 comfort settings (Home, Away, Sleep) be enough? It will be a LOT easier than also trying to implement the custom options for now.

I propose that I start with these three built-in options and then add the more flexible version later if it proves useful.

Thoughts?

**Comment by ncsufire** [comment]
Yes, start with the three supported modes.

**Comment by walksonair** [comment]
Yes, whatever the standard profiles are would be enough for now.

On Sat, Jan 16, 2016 at 00:49, StrykerSKS/SmartThingsPublic
reply@reply.github.com
wrote:
Question for all of you. Would supporting the built-in 3 comfort settings (Home,
Away, Sleep) be enough? It will be a LOT easier than also trying to implement
the custom options for now.

I propose that I start with these three built-in options and then add the more
flexible version later if it proves useful.

Thoughts?

—
Reply to this email directly or view it on GitHub
[https://github.com/StrykerSKS/SmartThingsPublic/issues/8#issuecomment-172173517] .[https://github.com/notifications/beacon/AOmH2E5flw3j8hygzAtUzTLO0o7NaQCHks5pafupgaJpZM4HAVWc.gif]

**Comment by gazzer82** [comment]
That would be perfect, I don't use any custom modes at the moment.

Thanks!

Sent from my iPhone

On Jan 16, 2016, at 06:41, walksonair <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, whatever the standard profiles are would be enough for now.

On Sat, Jan 16, 2016 at 00:49, StrykerSKS/SmartThingsPublic
<reply@reply.github.com<mailto:reply@reply.github.com>>
wrote:
Question for all of you. Would supporting the built-in 3 comfort settings (Home,
Away, Sleep) be enough? It will be a LOT easier than also trying to implement
the custom options for now.

I propose that I start with these three built-in options and then add the more
flexible version later if it proves useful.

Thoughts?

## 

Reply to this email directly or view it on GitHub
[https://github.com/StrykerSKS/SmartThingsPublic/issues/8#issuecomment-172173517] .[https://github.com/notifications/beacon/AOmH2E5flw3j8hygzAtUzTLO0o7NaQCHks5pafupgaJpZM4HAVWc.gifhttps://github.com/StrykerSKS/SmartThingsPublic/issues/8#issuecomment-172173517]%20.[https://github.com/notifications/beacon/AOmH2E5flw3j8hygzAtUzTLO0o7NaQCHks5pafupgaJpZM4HAVWc.gif]

##

**Comment by snakedog116** [comment]
Yes. I agree. Home away and sleep are the most important.

**Comment by StrykerSKS** [comment]
Beta version available for testing now on the StrykerSKS-enhanced-ecobee branch. Anyone wanting to get early access to testing can now try out the functionality.

**Comment by ncsufire** [comment]
Can you give me the link to the branch?  Still having issues with the GitHub integration so I will manually need to load it.

**Comment by ncsufire** [comment]
I put it through the test with both temporary and permeant holds and could see the settings change through the Ecobee app.  I would recommend that the 'Resume Schedule' tile get moved down with the comfort settings.  Thank you for this, are there any other tests that you want to run through before you close this item and push it to the main branch?

**Comment by StrykerSKS** [comment]
Thanks for that!

I'm going to leave all the UI changes for last since I'm also now adding in the fanModes support, so will need to tweek the UI once it is all finished up.

I'll go ahead and push this beta branch up to stable then. That way I can roll out a new beta hopefully tonight.

**Comment by ncsufire** [comment]
Great!  Are you planning on adding revision history  (even if this is not
retroactive) so people can see what version the code is on?  I know it is a
small detail but thought I would ask.

**Comment by StrykerSKS** [comment]
Yes, I'm going to start adding version numbers starting with this release. I also plan to create a Changelog of sorts.
