### ISSUE TITLE
Changing Modes on Ecobee 3 using Rule Machine

### ISSUE THREAD

**Issue by house002000** [StrykerSKS/SmartThingsPublic#9]
Does anyone have the problem using (Bruces)Rule Machine  to change  StrykerSKS ecobee 3 modes from Off to Heat and vice versa.

I  ran an experiment where I setup a rule machine to change Ecobee 3  mode to heat and set temperature to 71.
 After rule was executed  the temperature on thermostat was changed but the mode was still at off.

If I open  StrykerSKS device for Ecobee 3 in smartthings and change from off to heat then my thermostat will change from off to heat and vice versa.

Summary
 I can changes modes( Off/heat) from StrykerSKS device type for my  Ecobee 3, but cant change  Ecobee 3  modes when using rules from Rule Machine. 

Any comments
![image](https://cloud.githubusercontent.com/assets/16184284/12179315/e3197c38-b52a-11e5-9de4-4aedb88d424e.png)

![image](https://cloud.githubusercontent.com/assets/16184284/12179311/dc4c06be-b52a-11e5-89bd-5fa5ea15aacf.png)

**Comment by StrykerSKS** [comment]
Was able to trace this one back to a "stub" function in the original driver. Basically it is a piece of code that was never fully implemented:

'''
def setThermostatMode(String value) {
    log.debug "setThermostatMode(${value})"

}
'''

This one should be easy for me to fix, but I need some sleep for right now. Will come back to it tomorrow.

**Comment by StrykerSKS** [comment]
I have implemented the missing functions and have tested it with a basic rule (change the mode to heat). It worked for me.

Please install the latest versions from the StrykerSKS-Ecobee3 branch. Please update all three files (Thermostat, Sensor and Connect)

**Comment by house002000** [comment]
StrykerSKs
Please see smartthings community. I provided feedback on new code. Changing modes isn't working as expected.
